spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:tacocloud
    username: postgres
    password: telefon290787
  flyway:
    baseline-on-migrate: true
